spring:
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:36681/railway
    username: root
    password: 1BB6aHbbG14bG5b1e5GH6Egg6HHBFa3G
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types.pdf: application/pdf

  thymeleaf:
    mode: DEVELOPMENT
    cache: false

media-type:
  pdf:
    type: application
    subtype: pdf
    parameters:
      charset: UTF-8
