spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:27472/railway
    username: root
    password: 5gcG1fd6BBA6bbcD4-f42eEfEB-5b5d6
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types.pdf: application/pdf

media-type:
      pdf:
        type: application
        subtype: pdf
        parameters:
          charset: UTF-8
        