spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:27472/railway
    username: root
    password: 5gcG1fd6BBA6bbcD4-f42eEfEB-5b5d6
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
