spring:
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:56020/railway
    username: root
    password: 1A1B4bb-6-d6b-d4cDD6DbAbaF-CG3ed
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types.pdf: application/pdf
  
  thymeleaf:
    mode: DEVELOPMENT
    cache: false

media-type:
      pdf:
        type: application
        subtype: pdf
        parameters:
          charset: UTF-8
        
